### ISSUE TITLE
Error running under passenger

### ISSUE THREAD

**Issue by jaxxstorm** [xing/racktables_api#3]
I'm attempting to run this application under passenger with rvm. When I try query the API, I get an internal server error:

```
App 33962 stderr: [ 2014-04-01 06:49:06.9560 33979/0x000000018f5218(Worker 1) utils.rb:68 ]: *** Exception NoMethodError in Rack application object (undefined method `debug' for nil:NilClass) (process 33979, thread 0x000000018f5218(Worker 1)):
App 33962 stderr:       from /opt/racktables_api/vendor/bundle/ruby/2.1.0/bundler/gems/racktables_api-87d3cd7e805f/lib/racktables_api.rb:60:in `block (3 levels) in builder'
App 33962 stderr:       from /opt/racktables_api/vendor/bundle/ruby/2.1.0/bundler/gems/racktables_api-87d3cd7e805f/lib/statsd_fake.rb:79:in `call'
App 33962 stderr:       from /opt/racktables_api/vendor/bundle/ruby/2.1.0/bundler/gems/racktables_api-87d3cd7e805f/lib/statsd_fake.rb:79:in `send_stats'
App 33962 stderr:       from /opt/racktables_api/vendor/bundle/ruby/2.1.0/bundler/gems/racktables_api-87d3cd7e805f/lib/statsd_fake.rb:31:in `count'
App 33962 stderr:       from /opt/racktables_api/vendor/bundle/ruby/2.1.0/bundler/gems/racktables_api-87d3cd7e805f/lib/statsd_fake.rb:13:in `increment'
App 33962 stderr:       from /opt/racktables_api/vendor/bundle/ruby/2.1.0/bundler/gems/racktables_api-87d3cd7e805f/lib/client_counter.rb:10:in `block in call'
App 33962 stderr:       from /opt/racktables_api/vendor/bundle/ruby/2.1.0/bundler/gems/racktables_api-87d3cd7e805f/lib/logistician/context.rb:54:in `use'
App 33962 stderr:       from /opt/racktables_api/vendor/bundle/ruby/2.1.0/bundler/gems/racktables_api-87d3cd7e805f/lib/client_counter.rb:9:in `call'
App 33962 stderr:       from /opt/racktables_api/vendor/bundle/ruby/2.1.0/bundler/gems/racktables_api-87d3cd7e805f/lib/logistician/context.rb:37:in `call'
App 33962 stderr:       from /opt/racktables_api/vendor/bundle/ruby/2.1.0/bundler/gems/racktables_api-87d3cd7e805f/lib/logistician/context.rb:18:in `call'
App 33962 stderr:       from /opt/racktables_api/vendor/bundle/ruby/2.1.0/bundler/gems/racktables_api-87d3cd7e805f/lib/api_key_authenticator.rb:60:in `call'
App 33962 stderr:       from /opt/racktables_api/vendor/bundle/ruby/2.1.0/bundler/gems/racktables_api-87d3cd7e805f/lib/caller.rb:20:in `call'
App 33962 stderr:       from /opt/racktables_api/vendor/bundle/ruby/2.1.0/bundler/gems/racktables_api-87d3cd7e805f/lib/racktables_api.rb:44:in `block (2 levels) in builder'
App 33962 stderr:       from /opt/racktables_api/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/lint.rb:49:in `_call'
App 33962 stderr:       from /opt/racktables_api/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'
App 33962 stderr:       from /usr/local/rvm/gems/ruby-2.1.1/gems/passenger-4.0.40/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
App 33962 stderr:       from /usr/local/rvm/gems/ruby-2.1.1/gems/passenger-4.0.40/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
App 33962 stderr:       from /usr/local/rvm/gems/ruby-2.1.1/gems/passenger-4.0.40/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
App 33962 stderr:       from /usr/local/rvm/gems/ruby-2.1.1/gems/passenger-4.0.40/lib/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'
```

I'm also having trouble using ldap auth with AD, as I can only specify host and domain, and not search base, search attribute etc. Any way you can help?

**Comment by hannesg** [comment]
Sure, I'll have a look
